(suite predicates
       (suite bound
              t-for-assigned-variables (assert-t  ((fn () (assign foo 'bar) (bound 'foo))))
              nil-for-unset-items (assert-nil (bound 'toto-yadda))
              nil-for-local-parameters (assert-nil ((fn (yadda-toto) (bound 'yadda-toto)) "blah" )))
       (suite less-than
              first-number-less-than-second (assert-t (< 1 2))
              first-number-greater-than-second (assert-nil (< 20 5))
              first-number-equal-to-second (assert-nil (< 20 20))
              first-string-less-than-second (assert-t (< "bar" "foo"))
              first-string-greater-than-second (assert-nil (< "zizi" "alpha"))
              first-string-equal-to-second (assert-nil (< "foo" "foo"))
              first-symbol-less-than-second (assert-t (< 'bar 'foo))
              first-symbol-greater-than-second (assert-nil (< 'zizi 'alpha))
              first-symbol-equal-to-second (assert-nil (< 'foo 'foo))
              is-variadic (assert-t (< 1 2 3 4))
              variadic-works-beyond-two-args (assert-nil (< 1 2 10 4))
              is-variadic-on-characters (assert-t (< #\a #\c #\z))
              variadic-on-characters-works-beyond-two-args (assert-nil (< #\a #\b #\z #\d)))
       (suite greater-than
              first-number-less-than-second (assert-nil (> 1 2))
              first-number-greater-than-second (assert-t (> 20 5))
              first-number-equal-to-second (assert-nil (> 20 20))
              first-string-less-than-second (assert-nil (> "bar" "foo"))
              first-string-greater-than-second (assert-t (> "zizi" "alpha"))
              first-string-equal-to-second (assert-nil (> "foo" "foo"))
              first-symbol-less-than-second (assert-nil (> 'bar 'foo))
              first-symbol-greater-than-second (assert-t (> 'zizi 'alpha))
              first-symbol-equal-to-second (assert-nil (> 'foo 'foo))
              is-variadic (assert-t (> 4 3 2 1))
              variadic-works-beyond-two-args (assert-nil (> 4 3 22 1))
              is-variadic-on-characters (assert-t (> #\z #\c #\a))
              variadic-on-characters-works-beyond-two-args (assert-nil (> #\z #\y #\a #\w)))
       (suite exact
              integers (assert-t (exact 12))
              reals-arent-exact-even-if-are-ints (assert-nil (exact 12.0))
              rational-resulting-in-ints (assert-t (exact 12/4))
              rational-not-resulting-in-int (assert-nil (exact 12/5))
              floats (assert-nil (exact 3.14)))
       (suite is
              nil-nil (assert-t (is nil nil))
              t-t (assert-t (is t t))
              t-nil (assert-nil (is t nil))
              nil-t (assert-nil (is nil t))
              space-characters (assert-t (is #\space #\space))
              newline-characters (assert-t (is #\newline #\newline))
              same-ints (assert-t (is 2 2))
              same-rationals (assert-t (is 22/7 22/7))
              same-floats (assert-t (is 1.618 1.618))
              same-strings (assert-t (is "foobar" "foobar"))
              different-integers (assert-nil (is 2 3))
              same-numerical-value-different-types (assert-nil (is 3/4 0.75))
              different-floats (assert-nil (is 1.1234567 1.1234569))
              different-strings (assert-nil (is "foobar" "toto"))
              variadic-for-same-numbers (assert-t (is 1.23 1.23 1.23 1.23))
              variadic-for-different-numbers (assert-nil (is 1.23 1.23 1.23 3.14159265))
              variadic-for-same-strings (assert-t (is "f" "f" "f" "f" "f" "f"))
              variadic-for-different-strings (assert-nil (is "f" "f" "f" "g" "f" "f"))
              variadic-for-symbols (assert-t (is 'f 'f 'f 'f 'f 'f))
              variadic-for-different-symbols (assert-nil (is 'f 'f 'f 'g 'f 'f))
              identical-lists-are-different (assert-nil (is (list 'cons); see http://arclanguage.org/item?id=6985
                                                            (list 'cons)))
              empty-lists (assert-t (is '()
                                        '()))))
